name: Apply DB migrations

on:
  workflow_dispatch:
jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      
      - name: Restore dependencies
        run: | 
          dotnet tool install --global dotnet-ef
          dotnet tool restore

      - name: Apply migrations
        run: dotnet ef database update --startup-project src/Web.API/Web.API.csproj --project src/Infrastructure/Infrastructure.csproj --connection '${{ secrets.DATABASE_CONNECTION_STRING }}'
