name: Apply DB migrations

on:
  workflow_dispatch:

jobs:
  migrate_database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Restore dependencies and tools
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Apply migrations
        run: dotnet ef database update --startup-project src/Web.API/Web.API.csproj --project src/Infrastructure/Infrastructure.csproj
        env:
          DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}